version: '1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: antsa
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
